blank_issues_enabled: false
contact_links:
  - name: 📚 Documentação do Projeto
    url: https://github.com/UnBArqDsw2026-1-Turma02/2026.1_T02_G1_MadDev_Entrega_01
    about: Consulte a documentação completa do projeto MadDev